server:
  port: 9000
spring:
################数据库配置##############
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/xyls_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    #####jpa####
    jpa:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update


    #############frremark############
    http:
      encoding:
        force: true
        charset: UTF-8
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
    freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html; charset=utf-8
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      suffix: .html
      template-loader-path: classpath:/templates
    mvc:
      static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${xyls.security.file.fileDir}
##session集群#######
    redis:
      host: localhost
      port: 6379
      database: 0
      password: redis
    session:
      store-type: REDIS
      ##session超时时间
      timeout: 1800
#######禁用basic登录
security:
  basic:
    enabled: false

#上传文件资源路径
xyls:
  security:
    file:
      fileDir: D:/test/attached/
      url: /
    browser:
      session:
      ####不做session控制得url
        openUrl: /wechat/**
  output:
    ansi:
      enabled: always                     #控制台彩色



